# Generated by Django 4.2 on 2024-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_gif',
            field=models.BooleanField(default=True),
        ),
    ]
