# Generated by Django 4.2 on 2023-05-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('created_at',)},
        ),
    ]
