version: "3"

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: AnimatedTranslator
    restart: unless-stopped
    volumes:
      - .:/AnimatedTranslator
      - etc-letsencrypt:/etc/letsencrypt
    ports:
      - "8000:8000"
    networks:
      - postgres

volumes:
  etc-letsencrypt:

networks:
  postgres:
    driver: bridge
