# Generated by Django 4.2 on 2023-05-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0002_message_messageattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
    ]
